variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  PACKAGE_VERSION: "0.1.3"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/y_rb/${PACKAGE_VERSION}"

stages:
  - build
  - upload
  - release

build-linux:
  stage: build
  image: ruby:${RUBY_VERSION}
  script:
    - curl https://sh.rustup.rs -sSf | sh -s -- -y
    - source /builds/gitlab-org/incubation-engineering/real-time-editing/yrb/.cargo/env
    - gem install bundler
    - bundle install
    - bundle exec rake thermite:tarball
  artifacts:
    paths:
      - "y_rb-*.tar.gz"
  parallel:
    matrix:
      - RUBY_VERSION: ["2.6", "2.7", "3.0", "3.1"]

build-macos:
  stage: build
  image: ${IMAGE_VERSION}
  variables:
    HOMEBREW_NO_INSTALL_CLEANUP: 1
    HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
  cache:
    - key: "rvm"
    - paths:
        - /Users/gitlab/.rvm
  script:
    - /bin/bash -c "$(curl "https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh")"
    - brew install gnupg
    - curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -
    - curl -L https://get.rvm.io | bash -s stable
    - /bin/bash -l -c "rvm requirements"
    - /bin/bash -l -c "rvm install $RUBY_VERSION"
    - /bin/bash -l -c "rvm --default use $RUBY_VERSION"
    - curl https://sh.rustup.rs -sSf | sh -s -- -y
    - source /Users/gitlab/builds/gitlab-org/incubation-engineering/real-time-editing/yrb/.cargo/env
    - rustup target add aarch64-apple-darwin
    - rustup target add aarch64-unknown-linux-gnu
    - rustup target add x86_64-apple-darwin
    - gem install bundler
    - bundle install
    - bundle exec rake thermite:tarball
  tags: [ shared-macos-amd64 ]
  artifacts:
    paths:
      - "y_rb-*.tar.gz"
  parallel:
    matrix:
      - IMAGE_VERSION: ["macos-11-xcode-12", "macos-12-xcode-13"]
        RUBY_VERSION: ["2.6.10", "2.7.6", "3.0.4", "3.1.2"]

upload:
  stage: upload
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file y_rb-${PACKAGE_VERSION}-ruby27-linux-x86_64.tar.gz "${PACKAGE_REGISTRY_URL}/y_rb-${PACKAGE_VERSION}-ruby27-linux-x86_64.tar.gz"
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file y_rb-${PACKAGE_VERSION}-ruby30-linux-x86_64.tar.gz "${PACKAGE_REGISTRY_URL}/y_rb-${PACKAGE_VERSION}-ruby30-linux-x86_64.tar.gz"
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file y_rb-${PACKAGE_VERSION}-ruby31-linux-x86_64.tar.gz "${PACKAGE_REGISTRY_URL}/y_rb-${PACKAGE_VERSION}-ruby31-linux-x86_64.tar.gz"
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file y_rb-${PACKAGE_VERSION}-ruby27-darwin20-x86_64.tar.gz "${PACKAGE_REGISTRY_URL}/y_rb-${PACKAGE_VERSION}-ruby27-darwin20-x86_64.tar.gz"
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file y_rb-${PACKAGE_VERSION}-ruby30-darwin20-x86_64.tar.gz "${PACKAGE_REGISTRY_URL}/y_rb-${PACKAGE_VERSION}-ruby30-darwin20-x86_64.tar.gz"
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file y_rb-${PACKAGE_VERSION}-ruby31-darwin20-x86_64.tar.gz "${PACKAGE_REGISTRY_URL}/y_rb-${PACKAGE_VERSION}-ruby31-darwin20-x86_64.tar.gz"
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file y_rb-${PACKAGE_VERSION}-ruby27-darwin21-x86_64.tar.gz "${PACKAGE_REGISTRY_URL}/y_rb-${PACKAGE_VERSION}-ruby27-darwin21-x86_64.tar.gz"
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file y_rb-${PACKAGE_VERSION}-ruby30-darwin21-x86_64.tar.gz "${PACKAGE_REGISTRY_URL}/y_rb-${PACKAGE_VERSION}-ruby30-darwin21-x86_64.tar.gz"
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file y_rb-${PACKAGE_VERSION}-ruby31-darwin21-x86_64.tar.gz "${PACKAGE_REGISTRY_URL}/y_rb-${PACKAGE_VERSION}-ruby31-darwin21-x86_64.tar.gz"

release-gitlab:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      release-cli create --name "Release $CI_COMMIT_TAG" --tag-name "$CI_COMMIT_TAG" \
        --assets-link "{\"name\":\"y_rb-${PACKAGE_VERSION}-ruby26-linux-x86_64.tar.gz\",\"url\":\"${PACKAGE_REGISTRY_URL}/y_rb-${PACKAGE_VERSION}-ruby26-linux-x86_64.tar.gz\"}" \
        --assets-link "{\"name\":\"y_rb-${PACKAGE_VERSION}-ruby27-linux-x86_64.tar.gz\",\"url\":\"${PACKAGE_REGISTRY_URL}/y_rb-${PACKAGE_VERSION}-ruby27-linux-x86_64.tar.gz\"}" \
        --assets-link "{\"name\":\"y_rb-${PACKAGE_VERSION}-ruby30-linux-x86_64.tar.gz\",\"url\":\"${PACKAGE_REGISTRY_URL}/y_rb-${PACKAGE_VERSION}-ruby30-linux-x86_64.tar.gz\"}" \
        --assets-link "{\"name\":\"y_rb-${PACKAGE_VERSION}-ruby31-linux-x86_64.tar.gz\",\"url\":\"${PACKAGE_REGISTRY_URL}/y_rb-${PACKAGE_VERSION}-ruby31-linux-x86_64.tar.gz\"}" \
        --assets-link "{\"name\":\"y_rb-${PACKAGE_VERSION}-ruby26-darwin20-x86_64.tar.gz\",\"url\":\"${PACKAGE_REGISTRY_URL}/y_rb-${PACKAGE_VERSION}-ruby26-darwin20-x86_64.tar.gz\"}" \
        --assets-link "{\"name\":\"y_rb-${PACKAGE_VERSION}-ruby27-darwin20-x86_64.tar.gz\",\"url\":\"${PACKAGE_REGISTRY_URL}/y_rb-${PACKAGE_VERSION}-ruby27-darwin20-x86_64.tar.gz\"}" \
        --assets-link "{\"name\":\"y_rb-${PACKAGE_VERSION}-ruby30-darwin20-x86_64.tar.gz\",\"url\":\"${PACKAGE_REGISTRY_URL}/y_rb-${PACKAGE_VERSION}-ruby30-darwin20-x86_64.tar.gz\"}" \
        --assets-link "{\"name\":\"y_rb-${PACKAGE_VERSION}-ruby31-darwin20-x86_64.tar.gz\",\"url\":\"${PACKAGE_REGISTRY_URL}/y_rb-${PACKAGE_VERSION}-ruby31-darwin20-x86_64.tar.gz\"}" \
        --assets-link "{\"name\":\"y_rb-${PACKAGE_VERSION}-ruby26-darwin21-x86_64.tar.gz\",\"url\":\"${PACKAGE_REGISTRY_URL}/y_rb-${PACKAGE_VERSION}-ruby26-darwin21-x86_64.tar.gz\"}" \
        --assets-link "{\"name\":\"y_rb-${PACKAGE_VERSION}-ruby27-darwin21-x86_64.tar.gz\",\"url\":\"${PACKAGE_REGISTRY_URL}/y_rb-${PACKAGE_VERSION}-ruby27-darwin21-x86_64.tar.gz\"}" \
        --assets-link "{\"name\":\"y_rb-${PACKAGE_VERSION}-ruby30-darwin21-x86_64.tar.gz\",\"url\":\"${PACKAGE_REGISTRY_URL}/y_rb-${PACKAGE_VERSION}-ruby30-darwin21-x86_64.tar.gz\"}" \
        --assets-link "{\"name\":\"y_rb-${PACKAGE_VERSION}-ruby31-darwin21-x86_64.tar.gz\",\"url\":\"${PACKAGE_REGISTRY_URL}/y_rb-${PACKAGE_VERSION}-ruby31-darwin21-x86_64.tar.gz\"}"
