[package]
name = "yrb"
version = "0.4.0"
authors = ["Hannes Moser <box@hannesmoser.at>", "Hannes Moser <hmoser@gitlab.com>"]
edition = "2021"
homepage = "https://github.com/y-crdt/yrb"
repository = "https://github.com/y-crdt/yrb"

[dependencies]
lib0 = "0.14.1" # must match yrs version
magnus = { version = "0.4.4" }
thiserror = "1.0.38"
yrs = "0.14.1"

[dev-dependencies]
magnus = { version = "0.4.4", features = ["embed"] }

[lib]
name = "yrb"
crate-type = ["cdylib"]
