[package]
name = "yrb"
version = "0.5.1"
authors = ["Hannes Moser <box@hannesmoser.at>", "Hannes Moser <hmoser@gitlab.com>"]
edition = "2021"
homepage = "https://github.com/y-crdt/yrb"
repository = "https://github.com/y-crdt/yrb"

[dependencies]
lib0 = "0.16.8" # must match yrs version
magnus = "0.5.3"
thiserror = "1.0.40"
yrs = "0.16.5"
y-sync = "0.3.0"
rb-sys = "0.9.78"

[dev-dependencies]
magnus = { version = "0.5.3", features = ["embed"] }

[lib]
name = "yrb"
crate-type = ["cdylib"]
